apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-qy3r
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-qy3r@sha256:10dd473b8d2f4a38d246f9a636b08170fc7b8e533a9fe974ad1b800b3f579ae6
        name: my-python
        resources: {}
status: {}
